{{- if and .Values.kubeStateMetrics.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "kubeservice-monitor.kubeStateMetrics.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.kubeStateMetrics.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:  {{- include "kubeservice-monitor.kubeStateMetrics.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.kubeStateMetrics.replicaCount }}
  strategy: {{- toYaml .Values.kubeStateMetrics.updateStrategy | nindent 4 }}
  minReadySeconds: {{ .Values.kubeStateMetrics.minReadySeconds }}
  template:
    metadata:
      labels: {{- include "kubeservice-monitor.kubeStateMetrics.labels" . | nindent 8 }}
        {{- if .Values.kubeStateMetrics.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.kubeStateMetrics.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.kubeStateMetrics.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.kubeStateMetrics.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ template "kubeservice-monitor.kubeStateMetrics.serviceAccountName" . }}
      {{- if .Values.kubeStateMetrics.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.kubeStateMetrics.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.kubeStateMetrics.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.kubeStateMetrics.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.kubeStateMetrics.podAffinityPreset "component" "prometheus-operator" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.kubeStateMetrics.podAntiAffinityPreset "component" "prometheus-operator" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.kubeStateMetrics.nodeAffinityPreset.type "key" .Values.kubeStateMetrics.nodeAffinityPreset.key "values" .Values.kubeStateMetrics.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.kubeStateMetrics.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.kubeStateMetrics.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.kubeStateMetrics.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.kubeStateMetrics.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.kubeStateMetrics.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.kubeStateMetrics.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.kubeStateMetrics.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.kubeStateMetrics.terminationGracePeriodSeconds }}
      {{- end }}
      hostNetwork: {{ .Values.kubeStateMetrics.hostNetwork }}
      containers:
      - name: kube-state-metrics
        image: {{ template "kubeservice-monitor.kubeStateMetrics.image" . }}
        imagePullPolicy: {{ .Values.kubeStateMetrics.image.pullPolicy }}
        {{- if .Values.kubeStateMetrics.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.kubeStateMetrics.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
        args:
          {{- if .Values.kubeStateMetrics.kubeResources.certificatesigningrequests }}
          - --resources=certificatesigningrequests
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.configmaps }}
          - --resources=configmaps
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.cronjobs }}
          - --resources=cronjobs
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.daemonsets }}
          - --resources=daemonsets
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.deployments }}
          - --resources=deployments
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.endpoints }}
          - --resources=endpoints
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.horizontalpodautoscalers }}
          - --resources=horizontalpodautoscalers
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.ingresses }}
          - --resources=ingresses
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.jobs }}
          - --resources=jobs
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.limitranges }}
          - --resources=limitranges
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.mutatingwebhookconfigurations }}
          - --resources=mutatingwebhookconfigurations
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.namespaces }}
          - --resources=namespaces
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.networkpolicies }}
          - --resources=networkpolicies
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.nodes }}
          - --resources=nodes
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.persistentvolumeclaims }}
          - --resources=persistentvolumeclaims
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.persistentvolumes }}
          - --resources=persistentvolumes
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.poddisruptionbudgets }}
          - --resources=poddisruptionbudgets
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.pods }}
          - --resources=pods
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.replicasets }}
          - --resources=replicasets
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.replicationcontrollers }}
          - --resources=replicationcontrollers
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.resourcequotas }}
          - --resources=resourcequotas
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.secrets }}
          - --resources=secrets
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.services }}
          - --resources=services
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.statefulsets }}
          - --resources=statefulsets
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.storageclasses }}
          - --resources=storageclasses
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.verticalpodautoscalers }}
          - --resources=verticalpodautoscalers
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.validatingwebhookconfigurations }}
          - --resources=validatingwebhookconfigurations
          {{- end }}
          {{- if .Values.kubeStateMetrics.kubeResources.volumeattachments }}
          - --resources=volumeattachments
          {{- end }}
          {{- if .Values.namespaces }}
          - --namespaces={{- include "common.tplvalues.render" ( dict "value" .Values.namespaces "context" $ ) }}
          {{- end }}
          {{- range $key, $value := .Values.extraArgs }}
          {{- if $value }}
          - --{{ $key }}={{ $value }}
          {{- else }}
          - --{{ $key }}
          {{- end }}
          {{- end }}
        {{- if .Values.kubeStateMetrics.resources }}
        resources: {{- toYaml .Values.kubeStateMetrics.resources | nindent 12 }}
        {{- end }}
        ports:
          - name: {{ .Values.kubeStateMetrics.containerPorts.name }}
            containerPort: {{ .Values.kubeStateMetrics.containerPorts.port }}
            protocol: TCP
{{- end }}