{
 "title": "Kubernetes / Etcd",
 "description": "Etcd Dashboard for Prometheus  k8s-cn",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(etcd_server_is_leader,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Etcd leader 状态",
   "type": "stat",
   "description": "has_leader表示该成员是否具有leader 。如果某个成员没有leader ，则完全无法使用。如果群集中的所有成员都没有任何leader ，则整个群集完全不可用。",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "leader活动",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_leader_changes_seen_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "提交的共识proposals最大总数",
   "type": "gauge",
   "description": "proposals_committed_total记录已提交的共识提案的总数。如果群集健康，该指标应随时间增加。etcd集群的几个健康成员可能同时拥有不同的总承诺提议。这种差异可能是由于在开始后从同伴中恢复，落后于领导者，或者是领导者并因此具有最多的提交。在集群中的所有成员上监控此度量标准非常重要; 单个成员与其领导者之间的持续大滞后表明成员缓慢或不健康。",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_proposals_committed_total)"
    }
   ]
  },
  {
   "title": "unary 请求错误百分比/1minutes",
   "type": "gauge",
   "description": "对于job=\"foo\"，按服务计算失败请求的百分比。很容易注意到这是上述两个例子的组合。这是您希望在系统中警告 SLA违规的查询示例 ，例如“不超过1％的请求应该失败”。",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service) / sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[1m])) by (grpc_service) * 100.0)"
    }
   ]
  },
  {
   "title": "leader变化",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total[1d])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "平均响应流大小/10minutes",
   "type": "graph",
   "description": "对于所有RPC 返回的消息\ngrpc_service全局10m平均值是多少 server_stream。这允许您跟踪系统返回的流大小，例如，允许您跟踪客户端何时开始发送“宽”查询，以便记录除数是启动的RPC的数量，以便考虑到正在进行的请求。",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{grpc_type=\"server_stream\"}[10m])) by (grpc_service) / sum(rate(grpc_server_started_total{grpc_type=\"server_stream\"}[10m])) by (grpc_service)",
     "legendFormat": "{{ grpc_service }}"
    }
   ]
  },
  {
   "title": "unary 请求错误百分比/1minutes",
   "type": "graph",
   "description": "对于job=\"foo\"，按服务计算失败请求的百分比。很容易注意到这是上述两个例子的组合。这是您希望在系统中警告 SLA违规的查询示例 ，例如“不超过1％的请求应该失败”。",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service) / sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[1m])) by (grpc_service) * 100.0",
     "legendFormat": "{{ grpc_service }}"
    }
   ]
  },
  {
   "title": "请求进入速率/1minutes",
   "type": "graph",
   "description": "计算grpc_service作业所具有的每个gRPC的每秒请求率（1分钟窗口）。请注意grpc_method这里是如何省略的：给定gRPC服务的所有方法将汇总在一起",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total[1m])) by (grpc_service)",
     "legendFormat": "{{ grpc_service}}"
    }
   ]
  },
  {
   "title": "unary 请求错误率/1minutes",
   "type": "graph",
   "description": "计算失败grpc_service的unary（1：1）RPC的速率，即未完成OK代码的RPC 。",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)",
     "legendFormat": "{{ grpc_service }}"
    }
   ]
  },
  {
   "title": "RPC unary请求状态",
   "type": "graph",
   "description": "unary 是单一请求，单一响应RPC\nclient_stream 是一个多请求，单响应RPC\nserver_stream 是单个请求，多响应RPC\nbidi_stream 是一个多请求，多响应RPC",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC中单一请求unary总数"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "PRC中unary完成中失败的总数"
    }
   ]
  },
  {
   "title": "proposals",
   "type": "graph",
   "description": "proposals_applied_total记录所应用的共识提案总数。etcd服务器异步应用每个已提交的提议。proposals_committed_total和之间的差异proposals_applied_total通常很小（即使在高负荷下也只有几千）。如果它们之间的差异继续上升，则表明etcd服务器过载。在应用昂贵的查询（如重范围查询或大型txn操作）时可能会发生这种情况。",
   "gridPos": { "h": 10, "w": 13, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(etcd_server_proposals_committed_total) by (instance)",
     "legendFormat": "{{ instance }} /已提交proposals总数"
    },
    {
     "expr": "max(etcd_server_proposals_applied_total) by (instance)",
     "legendFormat": "{{ instance }} /应用proposals总数"
    }
   ]
  },
  {
   "title": "队列中的proposals提交数量",
   "type": "graph",
   "description": "上升的待定提议表明客户负载较高或成员无法提交提案",
   "gridPos": { "h": 10, "w": 3, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(etcd_server_proposals_pending) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "proposals_failed_total",
   "type": "graph",
   "description": "通常与两个问题有关：与领导者选举相关的临时故障或由于群集中的法定人数损失导致的更长停机时间。",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(etcd_server_proposals_failed_total) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "磁盘操作延迟",
   "type": "graph",
   "description": "高磁盘操作延迟（wal_fsync_duration_seconds或backend_commit_duration_seconds）通常表示磁盘问题。它可能会导致高请求延迟或使群集不稳定。",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance,le))",
     "legendFormat": "{{ instance }} WAL fsync "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{ instance }} DB fsync"
    }
   ]
  },
  {
   "title": "磁盘延迟详情",
   "type": "graph",
   "description": "一个wal_fsync被称为当ETCD应用之前仍然存在，它的日志条目到磁盘。一个backend_commit当ETCD提交的其最近的更改到磁盘的增量快照被调用。\n高磁盘操作延迟（wal_fsync_duration_seconds或backend_commit_duration_seconds）通常表示磁盘问题。它可能会导致高请求延迟或使群集不稳定。",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_disk_backend_commit_duration_seconds_count",
     "legendFormat": "{{  instance }} backend_commit/count"
    },
    {
     "expr": "etcd_disk_backend_commit_duration_seconds_sum",
     "legendFormat": "{{  instance }} backend_commit/sum"
    },
    {
     "expr": "etcd_disk_wal_fsync_duration_seconds_count",
     "legendFormat": "{{  instance }} wal_fsync/count"
    },
    {
     "expr": "etcd_disk_wal_fsync_duration_seconds_sum",
     "legendFormat": "{{  instance }} wal_fsync/sum"
    }
   ]
  },
  {
   "title": "调用提交延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum[1m]))",
     "legendFormat": "由wal调用的fsync延迟"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum[1m]))",
     "legendFormat": "后端调用的提交的延迟"
    }
   ]
  },
  {
   "title": "物理分配的底层数据库的总大小/bytes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_debugging_mvcc_db_total_size_in_bytes)"
    }
   ]
  },
  {
   "title": "活动流",
   "type": "graph",
   "description": "Watch事件:\t观看Watch发生的事件或发生的事件。输入和输出都是流; 输入流用于创建和取消观察者，输出流发送事件。一个WatchRPC可以同时监视多个键范围，多个Watch的流媒体事件。可以从最后一次压缩修订开始观察整个事件历史记录。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "grpc客户端发送/接收",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
     "legendFormat": "{{instance}} \t收到grpc客户端的总字节数"
    },
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} 发送给grpc客户端的总字节数"
    }
   ]
  },
  {
   "title": "网络发送接收失败总数",
   "type": "graph",
   "description": "peer_sent_failures_total\t来自具有ID的对等方的发送失败总数To。\npeer_received_failures_total\t来自具有ID的对等体的接收失败总数From",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_peer_sent_failures_total[5m])",
     "legendFormat": "{{instance}} 来自具有ID的对等方的发送失败总数"
    },
    {
     "expr": "rate(etcd_network_peer_received_failures_total[5m])",
     "legendFormat": "{{instance}} 来自具有ID的对等体的接收失败总数From"
    }
   ]
  },
  {
   "title": "peer网络计算发送到特定对等方的总字节数",
   "type": "graph",
   "description": "peer_sent_bytes_total计算发送到特定对等方的总字节数。通常，领导成员发送的数据多于其他成员，因为它负责传输复制的数据。",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} 发送总字节数"
    }
   ]
  },
  {
   "title": "peer计算从特定对等方接收的总字节数",
   "type": "graph",
   "description": "peer_received_bytes_total计算从特定对等方接收的总字节数。通常，关注成员仅从领导成员接收数据。",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} 接收总字节数"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job='$job'}) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "最大打开文件描述符数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(process_max_fds{job=\"$job\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "打开文件描述符的数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(process_open_fds{job=\"$job\"}) by (instance)",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "快照持续时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum[1m]))",
     "legendFormat": "快照调用的保存的总延迟分布"
    }
   ]
  }
 ]
}