{{- if and .Values.alertmanager.enabled .Values.alertmanager.pdb.create }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "kubeservice-monitor.alertmanager.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.alertmanager.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      alertmanager: {{ template "kubeservice-monitor.alertmanager.fullname" . }}
  {{- if .Values.alertmanager.pdb.minAvailable }}
  minAvailable: {{ .Values.alertmanager.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.alertmanager.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.alertmanager.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
