{{- if and .Values.alertmanager.enabled .Values.alertmanager.alertmanagerSecret.create  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubeservice-monitor.alertManagerSecret.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.alertmanager.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  alertmanager.yaml: {{ toYaml .Values.alertmanager.alertmanagerSecret.context | b64enc | quote }}
  {{- range $key, $val := .Values.alertmanager.alertmanagerSecret.templateFiles }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
