{{- if .Values.grafana.datasources.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubeservice-monitor.grafana.datasourceSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.grafana.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      {{- if .Values.grafana.sourceServiceName }}
      url: http://{{ .Values.grafana.sourceServiceName }}.{{ include "common.names.namespace" . }}.cluster.local
      {{ else }}
      url: {{ template "kubeservice-monitor.prometheus.fullname" . }}-system:9090
      {{- end }}
      access: proxy
      isDefault: true
      editable: false
      version: 1
{{- end }}
