{{- if .Values.operator.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "kubeservice-monitor.operator.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.operator.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "kubeservice-monitor.operator.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "kubeservice-monitor.operator.labels" . | nindent 8 }}
        {{- if .Values.operator.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.operator.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.operator.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.operator.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ template "kubeservice-monitor.operator.serviceAccountName" . }}
      {{- if .Values.operator.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.operator.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.operator.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.operator.podAffinityPreset "component" "prometheus-operator" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.operator.podAntiAffinityPreset "component" "prometheus-operator" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.operator.nodeAffinityPreset.type "key" .Values.operator.nodeAffinityPreset.key "values" .Values.operator.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.operator.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.operator.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.operator.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.operator.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.operator.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
      - name: prometheus-operator
        image: {{ template "kubeservice-monitor.operator-image" . }}
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        {{- if .Values.operator.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.operator.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
        args:
        {{- if .Values.operator.kubeletService.enabled }}
        - --kubelet-service={{ .Values.operator.kubeletService.namespace }}/{{ template "kubeservice-monitor.fullname" . }}-prometheus-operator-kubelet
        {{- end }}
        {{- if .Values.operator.logFormat }}
        - --log-format={{ .Values.operator.logFormat }}
        {{- end }}
        {{- if .Values.operator.logLevel }}
        - --log-level={{ .Values.operator.logLevel }}
        {{- end }}
        - --prometheus-config-reloader={{ template "kubeservice-monitor.prometheusConfigReloader.image" . }}
        ports:
        - containerPort: 8080
          name: http
        resources: {{- toYaml .Values.operator.resources | nindent 10 }}
      - args:
        - --logtostderr
        - --secure-listen-address=:8443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:8080/
        image: {{ template "kubeservice-monitor.prometheusKubeRbacProxy.image" .}}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources: {{- toYaml .Values.operator.prometheusKubeRbacProxy.resources | nindent 10 }}
        securityContext: {{- omit .Values.operator.prometheusKubeRbacProxy.containerSecurityContext "enabled" | toYaml | nindent 10 }}
{{- end }}