{{- if .Values.operator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeservice-monitor.operator.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.operator.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.operator.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.operator.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  {{- if semverCompare ">v1.20-0" (include "common.capabilities.kubeVersion" .) }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  clusterIP: None
  ports: {{- toYaml .Values.operator.service.ports | nindent 2 }}
  selector: {{- include "kubeservice-monitor.operator.matchLabels" . | nindent 4 }}
{{- end }}
