{{- if and .Values.nodeExporter.enabled .Values.nodeExporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeservice-monitor.nodeExporter.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.nodeExporter.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.nodeExporter.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.nodeExporter.serviceAccount.annotations "context" $) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.nodeExporter.serviceAccount.automountServiceAccountToken }}
{{- end }}
