{{- if and .Values.nodeExporter.enabled .Values.nodeExporter.rbac.create }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubeservice-monitor.nodeExporter.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.nodeExporter.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubeservice-monitor.nodeExporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubeservice-monitor.nodeExporter.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}