{{- if and .Values.metricsServer.enabled .Values.metricsServer.rbac.create }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "kubeservice-monitor.metricsServer.clusterRoleSystemName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.metricsServer.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - nodes
    - namespaces
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - nodes/metrics
  verbs:
    - get
    - create
{{- end -}}
