{{- if and .Values.metricsServer.enabled .Values.metricsServer.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeservice-monitor.metricsServer.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.metricsServer.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.metricsServer.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metricsServer.serviceAccount.annotations "context" $) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.metricsServer.serviceAccount.automountServiceAccountToken }}
{{- end -}}
