{{- if .Values.metricsServer.enabled }}
apiVersion: {{ include "common.capabilities.apiService.apiVersion" . }}
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.metricsServer.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  service:
    {{ if eq .Values.managedCluster false }}
    name: {{ template "kubeservice-monitor.metricsServer.fullname" . }}
    {{ else }}
    name: metrics-server
    {{- end }}
    namespace: {{ include "common.names.namespace" . | quote }}
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
{{- end -}}
