{{- if and  .Values.defaultRules.create    .Values.defaultRules.rules.customerRules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "kubeservice-monitor.customerRules.DefinitionsName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "kubeservice-monitor.customerRules.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: customer-recording-rules
    rules:
    - expr: |-
        sum(kube_node_status_allocatable{resource="memory", unit="byte"})/(1024*1024*1024)
      record: cluster:cluster_memTotal_GiB:sum
    - expr: |-
        sum(kube_node_status_allocatable{resource="memory", unit="byte"})
      record: cluster:cluster_memTotal_bytes:sum
    - expr: |-
        sum  by(node) (kube_node_status_allocatable{resource="memory", unit="byte"})/(1024*1024*1024)
      record: node:node_memTotal_GiB
    - expr: |-
        sum  by(node) (kube_node_status_allocatable{resource="memory", unit="byte"})
      record: node:node_memTotal_bytes
    - expr: |-
        sum (container_memory_working_set_bytes{container!=""}) / (1024*1024*1024)
      record: cluster:cluster_memUsed_GiB:sum
    - expr: |-
        sum (container_memory_working_set_bytes{container!=""})
      record: cluster:cluster_memUsed_bytes:sum
    - expr: |-
        sum  by(node) (container_memory_working_set_bytes{container!=""}) / (1024*1024*1024)
      record: node:node_memUsed_GiB
    - expr: |-
        sum by(node) (container_memory_working_set_bytes{container!=""})
      record: node:node_memUsed_bytes
    - expr: |-
        cluster:cluster_memTotal_GiB:sum - cluster:cluster_memUsed_GiB:sum
      record: cluster:cluster_memAvailable_GiB:sum
    - expr: |-
        cluster:cluster_memTotal_bytes:sum - cluster:cluster_memUsed_bytes:sum
      record: cluster:cluster_memAvailable_bytes:sum
    - expr: |-
        node:node_memTotal_GiB - node:node_memUsed_GiB
      record: node:node_memAvailable_GiB
    - expr: |-
        node:node_memTotal_bytes - node:node_memUsed_bytes
      record: node:node_memAvailable_bytes
    - expr: |-
        cluster:cluster_memUsed_bytes:sum / cluster:cluster_memTotal_bytes:sum * 100
      record: cluster:cluster_memory_utilisation:ratio
    - expr: |-
        node:node_memUsed_bytes / node:node_memTotal_bytes * 100
      record: node:node_memory_utilisation:ratio
      # disk
    - expr: |-
        sum(ceil(node_filesystem_size_bytes{device=~"/dev/.*", job=~".*node-exporter"}/(1024*1024))/1024)
      record: cluster:cluster_diskTotal_GiB:sum
    - expr: |-
        sum(ceil(node_filesystem_size_bytes{device=~"/dev/.*", job=~".*node-exporter"}/(1024*1024))/1024)by(instance)
      record: node:node_diskTotal_GiB
    - expr: |-
        sum(ceil(node_filesystem_avail_bytes{device=~"/dev/.*",job=~".*node-exporter"}/(1024*1024))/1024)
      record: cluster:cluster_diskFree_GiB:sum
    - expr: |-
        sum(ceil(node_filesystem_avail_bytes{device=~"/dev/.*",job=~".*node-exporter"}/(1024*1024))/1024)by(instance)
      record: node:node_diskFree_GiB
    - expr: |-
        cluster:cluster_diskTotal_GiB:sum - cluster:cluster_diskFree_GiB:sum
      record: cluster:cluster_diskUsed_GiB:sum
    - expr: |-
        node:node_diskTotal_GiB - node:node_diskFree_GiB
      record: node:node_diskUsed_GiB
    - expr: |-
        cluster:cluster_diskUsed_GiB:sum / cluster:cluster_diskTotal_GiB:sum * 100
      record: cluster:cluster_diskUtilisation:ratio
    - expr: |-
        node:node_diskUsed_GiB / node:node_diskTotal_GiB * 100
      record: node:node_diskUtilisation:ratio
      # cpu
    - expr: sum(kube_node_status_allocatable{resource="cpu", unit="core"})
      record: cluster:cluster_cpuTotal:sum
    - expr: sum(kube_node_status_allocatable{resource="cpu", unit="core"})by(node)
      record: node:node_cpuTotal
    - expr: sum (irate(container_cpu_usage_seconds_total{id="/"}[2m]))
      record: cluster:cluster_cpuUsed:sum
    - expr: sum (irate(container_cpu_usage_seconds_total{id="/"}[2m]))by(node)
      record: node:node_cpuUsed
    - expr: cluster:cluster_cpuUsed:sum / cluster:cluster_cpuTotal:sum * 100
      record: cluster:cluster_cpuUtilisation:ratio
    - expr: node:node_cpuUsed / node:node_cpuTotal * 100
      record: node:node_cpuUtilisation:ratio
      # network
    - expr: sum (rate(container_network_transmit_bytes_total[2m]))*8/1024/1024
      record: cluster:cluster_NetworkTransmit:Mib_S
    - expr: sum by(node) (rate(container_network_transmit_bytes_total[2m]))*8/1024/1024
      record: node:node_NetworkTransmit:Mib_S
    - expr: sum (rate(container_network_receive_bytes_total[2m]))*8/1024/1024
      record: cluster:cluster_NetworkReceive:Mib_S
    - expr: sum by(node) (rate(container_network_receive_bytes_total[2m]))*8/1024/1024
      record: node:node_NetworkReceive:Mib_S
    # pod 监控指标
    - expr: sum(kube_pod_container_resource_requests{resource="cpu", unit="core",container !="",container!="POD"}) by (pod,node,namespace)
      record: pod:pod_CpuRequests
    - expr: sum(kube_pod_container_resource_limits{resource="cpu", unit="core",container !="",container!="POD"}) by (pod,node,namespace)
      record: pod:pod_CpuLimits
    - expr: sum(irate(container_cpu_usage_seconds_total{container !="",container!="POD"}[2m])) by (pod,node,namespace)
      record: pod:pod_CpuUsed
    - expr: |-
        (sum by( namespace, container, pod) (irate(container_cpu_usage_seconds_total{container!=""}[5m])))
        /
        (sum by(namespace, container, pod) (container_spec_cpu_quota{container!=""}) / 100000) * 100
      record: container:container_cpuUtilisation:ratio
    - expr: sum(container:container_cpuUtilisation:ratio) by(pod,namespace)
      record: pod:pod_cpuUtilisation:ratio
    - expr: sum(kube_pod_container_resource_requests{resource="memory", unit="byte"}) by (pod,node,namespace)
      record: pod:pod_MemRequests_Bytes
    - expr: sum(kube_pod_container_resource_limits{resource="memory", unit="byte"}) by (pod,node,namespace)
      record: pod:pod_MemLimits_Bytes
    - expr: sum (container_memory_working_set_bytes{container !="",container!="POD"}) by (pod,node,namespace)
      record: pod:pod_MemUsed_Bytes
    - expr: ceil(pod:pod_MemRequests_Bytes / (1024*1024))
      record: pod:pod_MemRequests_MiB
    - expr: ceil(pod:pod_MemLimits_Bytes / (1024*1024))
      record: pod:pod_MemLimits_MiB
    - expr: ceil(pod:pod_MemUsed_Bytes / (1024*1024))
      record: pod:pod_MemUsed_MiB
    - expr: sum(sum(irate(container_network_receive_bytes_total{image!=""}[2m])) by (pod,namespace)* on(pod) group_right kube_pod_container_info) by(pod,namespace) *8/1024/1024
      record: pod:pod_NetworkReceive_Mib_S
    - expr: sum(sum(irate(container_network_transmit_bytes_total{image!=""}[2m])) by (pod,namespace)* on(pod) group_right kube_pod_container_info) by(pod,namespace) *8/1024/1024
      record: pod:pod_NetworkTransmit_Mib_S
    # 应用 监控指标
    - expr: sum(kube_pod_container_resource_requests{resource="cpu", unit="core",container !="",container!="POD"})
      record: cluster_App:cluster_App_CpuRequests
    - expr: sum(kube_pod_container_resource_limits{resource="cpu", unit="core",container !="",container!="POD"})
      record: cluster_App:cluster_App_CpuLimits
    - expr: sum(irate(container_cpu_usage_seconds_total{container !="",container!="POD"}[2m]))
      record: cluster_App:cluster_App_CpuUsed
    - expr: sum(kube_pod_container_resource_requests{resource="memory", unit="byte"})
      record: cluster_App:cluster_App_MemRequests_Bytes
    - expr: sum(kube_pod_container_resource_limits{resource="memory", unit="byte"})
      record: cluster_App:cluster_App_MemLimits_Bytes
    - expr: sum (container_memory_working_set_bytes{container !="",container!="POD"})
      record: cluster_App:cluster_App_MemUsed_Bytes
    - expr: sum(sum(irate(container_network_receive_bytes_total{image!=""}[2m])) by (pod,namespace)* on(pod) group_right kube_pod_container_info) *8/1024/1024
      record: cluster_App:cluster_App_NetworkReceive_Mib_S
    - expr: sum(sum(irate(container_network_transmit_bytes_total{image!=""}[2m])) by (pod,namespace)* on(pod) group_right kube_pod_container_info) *8/1024/1024
      record: cluster_App:cluster_App_NetworkTransmit_Mib_S
    # workload层面监控
    - expr: max(kube_deployment_spec_replicas) without (instance, pod,job)
      record: workload:deployment_ReplicasDesired
    - expr: min(kube_deployment_status_replicas_available) without (instance, pod,job)
      record: workload:deployment_ReplicasAvailable
    - expr: max(kube_statefulset_replicas) without (instance, pod,job)
      record: workload:statefulset_ReplicasDesired
    - expr: min(kube_statefulset_status_replicas) without (instance, pod,job)
      record: workload:statefulset_ReplicasAvailable
    - expr: sum(sum(kube_pod_container_resource_requests{resource="cpu", unit="core",container !="",container!="POD"})by (pod,namespace)* on(pod) group_right namespace_workload_pod:kube_pod_owner:relabel)by(workload,workload_type,namespace)
      record: workload:workload_CpuRequests
    - expr: sum(sum(kube_pod_container_resource_limits{resource="cpu", unit="core",container !="",container!="POD"})by (pod,namespace)* on(pod) group_right namespace_workload_pod:kube_pod_owner:relabel)by(workload,workload_type,namespace)
      record: workload:workload_CpuLimits
    - expr: sum(sum(irate(container_cpu_usage_seconds_total{container !="",container!="POD"}[2m]))by(namespace,pod)* on(pod) group_right namespace_workload_pod:kube_pod_owner:relabel)by(workload,workload_type,namespace)
      record: workload:workload_CpuUsed
    - expr: sum(sum(kube_pod_container_resource_requests{resource="memory", unit="byte"})by (pod,namespace)* on(pod) group_right namespace_workload_pod:kube_pod_owner:relabel)by(workload,workload_type,namespace)
      record: workload:workload_MemRequests_Bytes
    - expr: sum(sum(kube_pod_container_resource_limits{resource="memory", unit="byte"})by (pod,namespace)* on(pod) group_right namespace_workload_pod:kube_pod_owner:relabel)by(workload,workload_type,namespace)
      record: workload:workload_MemLimits_Bytes
    - expr: sum(sum(container_memory_working_set_bytes) by(namespace,pod)* on(pod) group_right namespace_workload_pod:kube_pod_owner:relabel)by(workload,workload_type,namespace)
      record: workload:workload_MemUsed_Bytes
    - expr: workload:workload_MemRequests_Bytes / (1024*1024)
      record: workload:workload_MemRequests_MiB
    - expr: workload:workload_MemLimits_Bytes / (1024*1024)
      record: workload:workload_MemLimits_MiB
    - expr: workload:workload_MemUsed_Bytes / (1024*1024)
      record: workload:workload_MemUsed_MiB
    - expr: workload:workload_MemRequests_Bytes / (1024*1024*1024)
      record: workload:workload_MemRequests_GiB
    - expr: workload:workload_MemLimits_Bytes / (1024*1024*1024)
      record: workload:workload_MemLimits_GiB
    - expr: workload:workload_MemUsed_Bytes / (1024*1024*1024)
      record: workload:workload_MemUsed_GiB
    - expr: sum(sum(irate(container_network_receive_bytes_total{image!=""}[2m])) by (pod,namespace)* on(pod) group_right namespace_workload_pod:kube_pod_owner:relabel)by(workload,workload_type,namespace) *8/1024/1024
      record: workload:workload_NetworkReceive_Mib_S
    - expr: sum(sum(irate(container_network_transmit_bytes_total{image!=""}[2m])) by (pod,namespace)* on(pod) group_right namespace_workload_pod:kube_pod_owner:relabel)by(workload,workload_type,namespace) *8/1024/1024
      record: workload:workload_NetworkTransmit_Mib_S
{{- end }}